create schema if not exists menu_content;

revoke all on schema menu_content from anon, authenticated;
revoke all on all tables in schema menu_content from anon, authenticated;
alter default privileges in schema menu_content revoke all on tables from anon, authenticated;

create table if not exists menu_content.menu_profiles (
  id text primary key check (id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  eyebrow text not null check (length(btrim(eyebrow)) > 0),
  title text not null check (length(btrim(title)) > 0),
  description text not null check (length(btrim(description)) > 0),
  info_title text not null check (length(btrim(info_title)) > 0)
);

create table if not exists menu_content.menu_profile_facts (
  profile_id text not null references menu_content.menu_profiles(id) on delete cascade,
  fact_id text not null check (fact_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  label text not null check (length(btrim(label)) > 0),
  value text not null check (length(btrim(value)) > 0),
  link_text text null,
  link_href text null,
  order_index integer not null check (order_index >= 0),
  primary key (profile_id, fact_id),
  unique (profile_id, order_index),
  constraint menu_profile_facts_link_pair_valid
    check ((link_text is null and link_href is null) or (link_text is not null and link_href is not null))
);

create table if not exists menu_content.menu_prices (
  pricing_key text primary key check (length(btrim(pricing_key)) > 0),
  kind text not null check (kind in ('fixed', 'included', 'variants')),
  amount integer null check (amount is null or amount >= 0),
  unique (pricing_key, kind),
  constraint menu_prices_kind_amount_valid check (
    (kind = 'fixed' and amount is not null)
    or (kind in ('included', 'variants') and amount is null)
  )
);

create table if not exists menu_content.menu_price_variants (
  pricing_key text not null,
  price_kind text not null default 'variants' check (price_kind = 'variants'),
  variant_id text not null check (variant_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(btrim(name)) > 0),
  amount integer not null check (amount >= 0),
  available boolean not null default true,
  order_index integer not null check (order_index >= 0),
  primary key (pricing_key, variant_id),
  unique (pricing_key, order_index),
  foreign key (pricing_key, price_kind)
    references menu_content.menu_prices(pricing_key, kind)
    on delete cascade
);

create table if not exists menu_content.menu_daily_items (
  id bigint generated by default as identity primary key,
  item_id text not null unique check (item_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(btrim(name)) > 0),
  description text null,
  available boolean not null default true,
  pricing_key text not null references menu_content.menu_prices(pricing_key),
  order_index integer not null unique check (order_index >= 0)
);

create table if not exists menu_content.menu_profile_service_settings (
  profile_id text primary key references menu_content.menu_profiles(id) on delete cascade,
  service_kind text not null check (service_kind in ('daily-menu', 'grill'))
);

create table if not exists menu_content.menu_catalog_sections (
  id bigint generated by default as identity primary key,
  section_id text not null unique check (section_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null check (length(btrim(title)) > 0),
  description text null,
  order_index integer not null unique check (order_index >= 0),
  content_kind text not null check (content_kind in ('items', 'groups')),
  presentation text not null default 'cards' check (presentation in ('cards', 'compact-list'))
);

create table if not exists menu_content.menu_catalog_groups (
  id bigint generated by default as identity primary key,
  section_id text not null references menu_content.menu_catalog_sections(section_id) on delete cascade,
  group_id text not null check (group_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null check (length(btrim(title)) > 0),
  description text null,
  pricing_key text null references menu_content.menu_prices(pricing_key),
  order_index integer not null check (order_index >= 0),
  unique (section_id, group_id),
  unique (section_id, order_index)
);

create table if not exists menu_content.menu_catalog_items (
  id bigint generated by default as identity primary key,
  section_id text not null references menu_content.menu_catalog_sections(section_id) on delete cascade,
  group_id text not null default '' check (group_id = '' or group_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  item_id text not null check (item_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(btrim(name)) > 0),
  description text null,
  image_path text null,
  available boolean not null default true,
  pricing_key text null references menu_content.menu_prices(pricing_key),
  order_index integer not null check (order_index >= 0),
  unique (section_id, group_id, item_id),
  unique (section_id, group_id, order_index)
);

create table if not exists menu_content.menu_catalog_item_options (
  catalog_item_id bigint not null references menu_content.menu_catalog_items(id) on delete cascade,
  option_id text not null check (option_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(btrim(name)) > 0),
  description text null,
  available boolean not null default true,
  order_index integer not null check (order_index >= 0),
  primary key (catalog_item_id, option_id),
  unique (catalog_item_id, order_index)
);

create table if not exists menu_content.menu_grill_families (
  family_id text primary key check (family_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null check (length(btrim(title)) > 0),
  order_index integer not null unique check (order_index >= 0)
);

create table if not exists menu_content.menu_grill_catalog_items (
  id bigint generated by default as identity primary key,
  family_id text not null references menu_content.menu_grill_families(family_id),
  item_id text not null unique check (item_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(btrim(name)) > 0),
  variant_name text null,
  description text null,
  image_path text null,
  available boolean not null default true,
  pricing_key text not null references menu_content.menu_prices(pricing_key),
  order_index integer not null unique check (order_index >= 0)
);

revoke all on all tables in schema menu_content from anon, authenticated;
revoke all on all sequences in schema menu_content from anon, authenticated;
