begin;

do $$
begin
  if to_regclass('public.staff_users') is null then
    raise exception 'public.staff_users is required before publish-menu-changes support can be installed.';
  end if;

  if not exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'can_publish_menu'
      and pg_get_function_identity_arguments(p.oid) = ''
  ) then
    raise exception 'public.can_publish_menu() is required before publish-menu-changes support can be installed.';
  end if;
end $$;

create schema if not exists app_private;

revoke all on schema app_private from public, anon, authenticated;
revoke all on all tables in schema app_private from public, anon, authenticated;
revoke all on all sequences in schema app_private from public, anon, authenticated;
alter default privileges in schema app_private revoke all on tables from public, anon, authenticated;
alter default privileges in schema app_private revoke all on sequences from public, anon, authenticated;

create table if not exists app_private.menu_publish_requests (
  id bigint generated by default as identity primary key,
  requested_by uuid null references auth.users(id) on delete set null,
  status text not null check (status in ('queued', 'cooldown', 'succeeded', 'failed')),
  message text not null check (length(btrim(message)) > 0 and length(message) <= 120),
  vercel_status_code integer null check (vercel_status_code is null or (vercel_status_code >= 100 and vercel_status_code <= 599)),
  vercel_job_id text null check (vercel_job_id is null or length(btrim(vercel_job_id)) > 0),
  created_at timestamptz not null default now(),
  completed_at timestamptz null,
  updated_at timestamptz not null default now()
);

create index if not exists menu_publish_requests_recent_publish_idx
  on app_private.menu_publish_requests (created_at desc)
  where status in ('queued', 'succeeded');

create index if not exists menu_publish_requests_requested_by_idx
  on app_private.menu_publish_requests (requested_by, created_at desc);

alter table app_private.menu_publish_requests enable row level security;

revoke all on app_private.menu_publish_requests from public, anon, authenticated;
revoke all on sequence app_private.menu_publish_requests_id_seq from public, anon, authenticated;

create or replace function public.reserve_menu_publish_request(
  user_id uuid,
  cooldown_seconds integer
)
returns table (
  request_id bigint,
  reserved boolean,
  message text
)
language plpgsql
security definer
set search_path = public, app_private, pg_temp
as $$
declare
  effective_cooldown_seconds integer := least(greatest(coalesce(cooldown_seconds, 60), 0), 3600);
  inserted_request_id bigint;
  recent_request_id bigint;
begin
  if user_id is null then
    return query select null::bigint, false, 'user_id_required'::text;
    return;
  end if;

  perform pg_advisory_xact_lock(hashtext('publish_menu_changes')::bigint);

  select request.id
  into recent_request_id
  from app_private.menu_publish_requests request
  where request.status in ('queued', 'succeeded')
    and request.created_at >= now() - make_interval(secs => effective_cooldown_seconds)
  order by request.created_at desc
  limit 1;

  if recent_request_id is not null then
    insert into app_private.menu_publish_requests (
      requested_by,
      status,
      message
    )
    values (
      reserve_menu_publish_request.user_id,
      'cooldown',
      'publish_recently_queued'
    )
    returning id into inserted_request_id;

    return query select inserted_request_id, false, 'publish_recently_queued'::text;
    return;
  end if;

  insert into app_private.menu_publish_requests (
    requested_by,
    status,
    message
  )
  values (
    reserve_menu_publish_request.user_id,
    'queued',
    'publish_reserved'
  )
  returning id into inserted_request_id;

  return query select inserted_request_id, true, 'publish_reserved'::text;
end;
$$;

create or replace function public.complete_menu_publish_request(
  request_id bigint,
  publish_status text,
  publish_message text,
  vercel_status_code integer,
  vercel_job_id text
)
returns table (
  completed boolean,
  message text
)
language plpgsql
security definer
set search_path = public, app_private, pg_temp
as $$
declare
  updated_count integer := 0;
  normalized_status text := nullif(btrim(publish_status), '');
  normalized_message text := left(coalesce(nullif(btrim(publish_message), ''), 'publish_completed'), 120);
  normalized_vercel_job_id text := nullif(btrim(vercel_job_id), '');
begin
  if request_id is null then
    return query select false, 'request_id_required'::text;
    return;
  end if;

  if normalized_status not in ('succeeded', 'failed') then
    return query select false, 'invalid_publish_status'::text;
    return;
  end if;

  if vercel_status_code is not null and (vercel_status_code < 100 or vercel_status_code > 599) then
    return query select false, 'invalid_vercel_status_code'::text;
    return;
  end if;

  update app_private.menu_publish_requests request
  set
    status = normalized_status,
    message = normalized_message,
    vercel_status_code = complete_menu_publish_request.vercel_status_code,
    vercel_job_id = normalized_vercel_job_id,
    completed_at = now(),
    updated_at = now()
  where request.id = complete_menu_publish_request.request_id
    and request.status = 'queued';

  get diagnostics updated_count = row_count;

  if updated_count = 0 then
    return query select false, 'request_not_queued'::text;
    return;
  end if;

  return query select true, 'publish_request_completed'::text;
end;
$$;

revoke all on function public.reserve_menu_publish_request(uuid, integer) from public, anon, authenticated, service_role;
revoke all on function public.complete_menu_publish_request(bigint, text, text, integer, text) from public, anon, authenticated, service_role;
grant execute on function public.reserve_menu_publish_request(uuid, integer) to service_role;
grant execute on function public.complete_menu_publish_request(bigint, text, text, integer, text) to service_role;

commit;
