begin;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'menu_content.menu_prices'::regclass
      and conname = 'menu_prices_kind_amount_valid'
  ) then
    alter table menu_content.menu_prices
      add constraint menu_prices_kind_amount_valid check (
        (kind = 'fixed' and amount is not null)
        or (kind in ('included', 'variants') and amount is null)
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'menu_content.menu_profile_facts'::regclass
      and conname = 'menu_profile_facts_link_pair_valid'
  ) then
    alter table menu_content.menu_profile_facts
      add constraint menu_profile_facts_link_pair_valid check (
        (link_text is null and link_href is null)
        or (link_text is not null and link_href is not null)
      );
  end if;
end $$;

create table if not exists menu_content.menu_daily_items (
  id bigint generated by default as identity primary key,
  item_id text not null unique check (item_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(btrim(name)) > 0),
  description text null,
  note text null,
  available boolean not null default true,
  pricing_key text not null references menu_content.menu_prices(pricing_key),
  order_index integer not null unique check (order_index >= 0)
);

create table if not exists menu_content.menu_profile_service_settings (
  profile_id text primary key references menu_content.menu_profiles(id) on delete cascade,
  service_kind text not null check (service_kind in ('daily-menu', 'grill'))
);

create table if not exists menu_content.menu_catalog_sections (
  id bigint generated by default as identity primary key,
  section_id text not null unique check (section_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null check (length(btrim(title)) > 0),
  description text null,
  note text null,
  order_index integer not null unique check (order_index >= 0),
  content_kind text not null check (content_kind in ('items', 'groups')),
  presentation text not null default 'cards' check (presentation in ('cards', 'compact-list'))
);

create table if not exists menu_content.menu_catalog_groups (
  id bigint generated by default as identity primary key,
  section_id text not null references menu_content.menu_catalog_sections(section_id) on delete cascade,
  group_id text not null check (group_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null check (length(btrim(title)) > 0),
  description text null,
  note text null,
  pricing_key text null references menu_content.menu_prices(pricing_key),
  order_index integer not null check (order_index >= 0),
  unique (section_id, group_id),
  unique (section_id, order_index)
);

create table if not exists menu_content.menu_catalog_items (
  id bigint generated by default as identity primary key,
  section_id text not null references menu_content.menu_catalog_sections(section_id) on delete cascade,
  group_id text not null default '' check (group_id = '' or group_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  item_id text not null check (item_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(btrim(name)) > 0),
  description text null,
  note text null,
  image_path text null,
  available boolean not null default true,
  pricing_key text null references menu_content.menu_prices(pricing_key),
  order_index integer not null check (order_index >= 0),
  unique (section_id, group_id, item_id),
  unique (section_id, group_id, order_index),
  unique (id, item_id)
);

create table if not exists menu_content.menu_catalog_item_options (
  catalog_item_id bigint not null references menu_content.menu_catalog_items(id) on delete cascade,
  option_id text not null check (option_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(btrim(name)) > 0),
  description text null,
  note text null,
  available boolean not null default true,
  order_index integer not null check (order_index >= 0),
  primary key (catalog_item_id, option_id),
  unique (catalog_item_id, order_index)
);

create table if not exists menu_content.menu_grill_families (
  family_id text primary key check (family_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null check (length(btrim(title)) > 0),
  order_index integer not null unique check (order_index >= 0)
);

create table if not exists menu_content.menu_grill_catalog_items (
  id bigint generated by default as identity primary key,
  family_id text not null references menu_content.menu_grill_families(family_id),
  item_id text not null unique check (item_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(btrim(name)) > 0),
  description text null,
  note text null,
  image_path text null,
  available boolean not null default true,
  pricing_key text not null references menu_content.menu_prices(pricing_key),
  order_index integer not null unique check (order_index >= 0)
);

create unique index if not exists menu_price_variants_pricing_key_order_key
  on menu_content.menu_price_variants (pricing_key, order_index);

create unique index if not exists menu_daily_items_item_id_key
  on menu_content.menu_daily_items (item_id);

create unique index if not exists menu_daily_items_order_key
  on menu_content.menu_daily_items (order_index);

create unique index if not exists menu_profile_service_settings_profile_key
  on menu_content.menu_profile_service_settings (profile_id);

create unique index if not exists menu_catalog_sections_section_id_key
  on menu_content.menu_catalog_sections (section_id);

create unique index if not exists menu_catalog_sections_order_key
  on menu_content.menu_catalog_sections (order_index);

create unique index if not exists menu_catalog_groups_section_group_id_key
  on menu_content.menu_catalog_groups (section_id, group_id);

create unique index if not exists menu_catalog_groups_section_order_key
  on menu_content.menu_catalog_groups (section_id, order_index);

create unique index if not exists menu_catalog_items_context_item_id_key
  on menu_content.menu_catalog_items (section_id, group_id, item_id);

create unique index if not exists menu_catalog_items_context_order_key
  on menu_content.menu_catalog_items (section_id, group_id, order_index);

create unique index if not exists menu_catalog_item_options_item_order_key
  on menu_content.menu_catalog_item_options (catalog_item_id, order_index);

create unique index if not exists menu_grill_families_order_key
  on menu_content.menu_grill_families (order_index);

create unique index if not exists menu_grill_catalog_items_item_id_key
  on menu_content.menu_grill_catalog_items (item_id);

create unique index if not exists menu_grill_catalog_items_order_key
  on menu_content.menu_grill_catalog_items (order_index);

insert into menu_content.menu_daily_items (
  item_id,
  name,
  description,
  note,
  available,
  pricing_key,
  order_index
)
select
  'menu-del-dia',
  daily.name,
  daily.description,
  daily.note,
  daily.available,
  daily.pricing_key,
  0
from menu_content.menu_daily_menu daily
where daily.id = 'current'
on conflict (item_id) do update
set
  name = excluded.name,
  description = excluded.description,
  note = excluded.note,
  available = excluded.available,
  pricing_key = excluded.pricing_key,
  order_index = excluded.order_index;

insert into menu_content.menu_daily_items (
  item_id,
  name,
  description,
  note,
  available,
  pricing_key,
  order_index
)
select
  generated_items.item_id,
  generated_items.name,
  null,
  null,
  daily.available,
  generated_items.pricing_key,
  generated_items.order_index
from menu_content.menu_daily_menu daily
cross join (
  values
    ('menu-del-dia-con-bebida', 'Menu del dia + bebida', 'menu-del-dia-con-bebida', 1),
    ('menu-vegetariano-del-dia', 'Menu del dia vegetariano', 'menu-vegetariano-del-dia', 2)
) as generated_items (item_id, name, pricing_key, order_index)
where daily.id = 'current'
on conflict (item_id) do update
set
  name = excluded.name,
  description = excluded.description,
  note = excluded.note,
  available = excluded.available,
  pricing_key = excluded.pricing_key,
  order_index = excluded.order_index;

insert into menu_content.menu_profile_service_settings (
  profile_id,
  service_kind
)
select
  profile_id,
  case when grill_enabled then 'grill' else 'daily-menu' end
from menu_content.menu_daily_service_settings
on conflict (profile_id) do update
set service_kind = excluded.service_kind;

insert into menu_content.menu_catalog_sections (
  section_id,
  title,
  description,
  note,
  order_index,
  content_kind,
  presentation
)
select
  section_id,
  title,
  description,
  note,
  order_index,
  content_kind,
  'cards'
from menu_content.menu_sections
on conflict (section_id) do update
set
  title = excluded.title,
  description = excluded.description,
  note = excluded.note,
  order_index = excluded.order_index,
  content_kind = excluded.content_kind,
  presentation = excluded.presentation;

insert into menu_content.menu_catalog_groups (
  section_id,
  group_id,
  title,
  description,
  note,
  pricing_key,
  order_index
)
select
  section.section_id,
  menu_group.group_id,
  menu_group.title,
  menu_group.description,
  menu_group.note,
  menu_group.pricing_key,
  menu_group.order_index
from menu_content.menu_groups menu_group
join menu_content.menu_sections section
  on section.id = menu_group.section_row_id
on conflict (section_id, group_id) do update
set
  title = excluded.title,
  description = excluded.description,
  note = excluded.note,
  pricing_key = excluded.pricing_key,
  order_index = excluded.order_index;

insert into menu_content.menu_catalog_items (
  section_id,
  group_id,
  item_id,
  name,
  description,
  note,
  image_path,
  available,
  pricing_key,
  order_index
)
select
  section.section_id,
  '',
  section_item.item_id,
  item.name,
  item.description,
  section_item.note,
  item.image_path,
  section_item.available,
  section_item.pricing_key,
  section_item.order_index
from menu_content.menu_section_items section_item
join menu_content.menu_sections section
  on section.id = section_item.section_row_id
join menu_content.menu_items item
  on item.id = section_item.item_row_id
 and item.item_id = section_item.item_id
on conflict (section_id, group_id, item_id) do update
set
  name = excluded.name,
  description = excluded.description,
  note = excluded.note,
  image_path = excluded.image_path,
  available = excluded.available,
  pricing_key = excluded.pricing_key,
  order_index = excluded.order_index;

insert into menu_content.menu_catalog_items (
  section_id,
  group_id,
  item_id,
  name,
  description,
  note,
  image_path,
  available,
  pricing_key,
  order_index
)
select
  section.section_id,
  menu_group.group_id,
  group_item.item_id,
  item.name,
  item.description,
  group_item.note,
  item.image_path,
  group_item.available,
  group_item.pricing_key,
  group_item.order_index
from menu_content.menu_group_items group_item
join menu_content.menu_groups menu_group
  on menu_group.id = group_item.group_row_id
join menu_content.menu_sections section
  on section.id = menu_group.section_row_id
join menu_content.menu_items item
  on item.id = group_item.item_row_id
 and item.item_id = group_item.item_id
on conflict (section_id, group_id, item_id) do update
set
  name = excluded.name,
  description = excluded.description,
  note = excluded.note,
  image_path = excluded.image_path,
  available = excluded.available,
  pricing_key = excluded.pricing_key,
  order_index = excluded.order_index;

insert into menu_content.menu_catalog_item_options (
  catalog_item_id,
  option_id,
  name,
  description,
  note,
  available,
  order_index
)
select
  catalog_item.id,
  option.option_id,
  option.name,
  option.description,
  option.note,
  option.available,
  option.order_index
from menu_content.menu_catalog_items catalog_item
join menu_content.menu_section_items section_item
  on section_item.item_id = catalog_item.item_id
join menu_content.menu_sections section
  on section.id = section_item.section_row_id
 and section.section_id = catalog_item.section_id
join menu_content.menu_item_options option
  on option.item_row_id = section_item.item_row_id
where catalog_item.group_id = ''
on conflict (catalog_item_id, option_id) do update
set
  name = excluded.name,
  description = excluded.description,
  note = excluded.note,
  available = excluded.available,
  order_index = excluded.order_index;

insert into menu_content.menu_catalog_item_options (
  catalog_item_id,
  option_id,
  name,
  description,
  note,
  available,
  order_index
)
select
  catalog_item.id,
  option.option_id,
  option.name,
  option.description,
  option.note,
  option.available,
  option.order_index
from menu_content.menu_catalog_items catalog_item
join menu_content.menu_group_items group_item
  on group_item.item_id = catalog_item.item_id
join menu_content.menu_groups menu_group
  on menu_group.id = group_item.group_row_id
 and menu_group.group_id = catalog_item.group_id
join menu_content.menu_sections section
  on section.id = menu_group.section_row_id
 and section.section_id = catalog_item.section_id
join menu_content.menu_item_options option
  on option.item_row_id = group_item.item_row_id
where catalog_item.group_id <> ''
on conflict (catalog_item_id, option_id) do update
set
  name = excluded.name,
  description = excluded.description,
  note = excluded.note,
  available = excluded.available,
  order_index = excluded.order_index;

insert into menu_content.menu_grill_families (
  family_id,
  title,
  order_index
)
values
  ('choripan', 'Choripan', 0),
  ('hamburguesa', 'Hamburguesa', 1),
  ('bondiola', 'Bondiola', 2),
  ('matambre', 'Matambre', 3),
  ('entrana', 'Entrana', 4),
  ('lomo', 'Lomo', 5),
  ('bife-chorizo', 'Bife de chorizo', 6),
  ('otros', 'Otros', 7)
on conflict (family_id) do update
set
  title = excluded.title,
  order_index = excluded.order_index;

insert into menu_content.menu_grill_catalog_items (
  family_id,
  item_id,
  name,
  description,
  note,
  image_path,
  available,
  pricing_key,
  order_index
)
select
  case
    when grill_item.item_id like '%choripan%' then 'choripan'
    when grill_item.item_id like '%hamburguesa%' then 'hamburguesa'
    when grill_item.item_id like '%bondiola%' then 'bondiola'
    when grill_item.item_id like '%matambre%' then 'matambre'
    when grill_item.item_id like '%entrana%' then 'entrana'
    when grill_item.item_id like '%lomo%' then 'lomo'
    when grill_item.item_id like '%bife-chorizo%' then 'bife-chorizo'
    else 'otros'
  end,
  grill_item.item_id,
  item.name,
  item.description,
  grill_item.note,
  item.image_path,
  grill_item.available,
  grill_item.pricing_key,
  grill_item.order_index
from menu_content.menu_grill_items grill_item
join menu_content.menu_items item
  on item.id = grill_item.item_row_id
 and item.item_id = grill_item.item_id
on conflict (item_id) do update
set
  family_id = excluded.family_id,
  name = excluded.name,
  description = excluded.description,
  note = excluded.note,
  image_path = excluded.image_path,
  available = excluded.available,
  pricing_key = excluded.pricing_key,
  order_index = excluded.order_index;

revoke all on all tables in schema menu_content from anon, authenticated;
revoke all on all sequences in schema menu_content from anon, authenticated;

commit;
