create schema if not exists menu_content;

revoke all on schema menu_content from anon, authenticated;
revoke all on all tables in schema menu_content from anon, authenticated;
alter default privileges in schema menu_content revoke all on tables from anon, authenticated;

create table if not exists menu_content.menu_profiles (
  id text primary key check (id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  eyebrow text not null check (length(btrim(eyebrow)) > 0),
  title text not null check (length(btrim(title)) > 0),
  description text not null check (length(btrim(description)) > 0),
  info_title text not null check (length(btrim(info_title)) > 0)
);

create table if not exists menu_content.menu_profile_facts (
  profile_id text not null references menu_content.menu_profiles(id) on delete cascade,
  fact_id text not null check (fact_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  label text not null check (length(btrim(label)) > 0),
  value text not null check (length(btrim(value)) > 0),
  link_text text null,
  link_href text null,
  order_index integer not null check (order_index >= 0),
  primary key (profile_id, fact_id),
  unique (profile_id, order_index),
  check ((link_text is null and link_href is null) or (link_text is not null and link_href is not null))
);

create table if not exists menu_content.menu_profile_payments (
  profile_id text primary key references menu_content.menu_profiles(id) on delete cascade,
  payment_id text not null check (payment_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  label text not null check (length(btrim(label)) > 0)
);

create table if not exists menu_content.menu_profile_payment_methods (
  profile_id text not null references menu_content.menu_profile_payments(profile_id) on delete cascade,
  method text not null check (length(btrim(method)) > 0),
  order_index integer not null check (order_index >= 0),
  primary key (profile_id, order_index)
);

create table if not exists menu_content.menu_prices (
  pricing_key text primary key check (length(btrim(pricing_key)) > 0),
  kind text not null check (kind in ('fixed', 'included', 'variants')),
  amount integer null check (amount is null or amount >= 0),
  currency text not null default 'ARS' check (currency = 'ARS'),
  unique (pricing_key, kind),
  check (
    (kind = 'fixed' and amount is not null)
    or (kind in ('included', 'variants') and amount is null)
  )
);

create table if not exists menu_content.menu_price_variants (
  pricing_key text not null,
  price_kind text not null default 'variants' check (price_kind = 'variants'),
  variant_id text not null check (variant_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(btrim(name)) > 0),
  amount integer not null check (amount >= 0),
  available boolean not null default true,
  order_index integer not null check (order_index >= 0),
  primary key (pricing_key, variant_id),
  unique (pricing_key, order_index),
  foreign key (pricing_key, price_kind)
    references menu_content.menu_prices(pricing_key, kind)
    on delete cascade
);

create table if not exists menu_content.menu_sections (
  id bigint generated by default as identity primary key,
  section_key text not null unique check (length(btrim(section_key)) > 0),
  section_scope text not null check (section_scope in ('catalog', 'daily')),
  menu_id text null references menu_content.menu_profiles(id) on delete cascade,
  section_id text not null check (section_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null check (length(btrim(title)) > 0),
  description text null,
  note text null,
  order_index integer not null check (order_index >= 0),
  content_kind text not null check (content_kind in ('items', 'groups')),
  check (
    (section_scope = 'catalog' and menu_id is null)
    or (section_scope = 'daily' and menu_id is not null)
  )
);

create unique index if not exists menu_sections_context_section_id_key
  on menu_content.menu_sections (section_scope, coalesce(menu_id, ''), section_id);

create unique index if not exists menu_sections_context_order_key
  on menu_content.menu_sections (section_scope, coalesce(menu_id, ''), order_index);

create table if not exists menu_content.menu_groups (
  id bigint generated by default as identity primary key,
  group_key text not null unique check (length(btrim(group_key)) > 0),
  section_row_id bigint not null references menu_content.menu_sections(id) on delete cascade,
  group_id text not null check (group_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  title text not null check (length(btrim(title)) > 0),
  description text null,
  note text null,
  pricing_key text null references menu_content.menu_prices(pricing_key),
  order_index integer not null check (order_index >= 0),
  unique (section_row_id, group_id),
  unique (section_row_id, order_index)
);

create table if not exists menu_content.menu_items (
  id bigint generated by default as identity primary key,
  item_key text not null unique check (length(btrim(item_key)) > 0),
  item_id text not null check (item_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(btrim(name)) > 0),
  description text null,
  image_path text null,
  unique (id, item_id)
);

create table if not exists menu_content.menu_section_items (
  id bigint generated by default as identity primary key,
  section_item_key text not null unique check (length(btrim(section_item_key)) > 0),
  section_row_id bigint not null references menu_content.menu_sections(id) on delete cascade,
  item_row_id bigint not null,
  item_id text not null check (item_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  order_index integer not null check (order_index >= 0),
  available boolean not null,
  note text null,
  pricing_key text null references menu_content.menu_prices(pricing_key),
  unique (section_row_id, item_id),
  unique (section_row_id, order_index),
  foreign key (item_row_id, item_id)
    references menu_content.menu_items(id, item_id)
    on delete cascade
);

create table if not exists menu_content.menu_group_items (
  id bigint generated by default as identity primary key,
  group_item_key text not null unique check (length(btrim(group_item_key)) > 0),
  group_row_id bigint not null references menu_content.menu_groups(id) on delete cascade,
  item_row_id bigint not null,
  item_id text not null check (item_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  order_index integer not null check (order_index >= 0),
  available boolean not null,
  note text null,
  pricing_key text null references menu_content.menu_prices(pricing_key),
  unique (group_row_id, item_id),
  unique (group_row_id, order_index),
  foreign key (item_row_id, item_id)
    references menu_content.menu_items(id, item_id)
    on delete cascade
);

create table if not exists menu_content.menu_item_options (
  item_row_id bigint not null references menu_content.menu_items(id) on delete cascade,
  option_id text not null check (option_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null check (length(btrim(name)) > 0),
  description text null,
  note text null,
  available boolean not null default true,
  order_index integer not null check (order_index >= 0),
  primary key (item_row_id, option_id),
  unique (item_row_id, order_index)
);

create table if not exists menu_content.menu_overrides (
  id bigint generated by default as identity primary key,
  override_key text not null unique check (length(btrim(override_key)) > 0),
  menu_id text not null references menu_content.menu_profiles(id) on delete cascade,
  unique (menu_id)
);

create table if not exists menu_content.menu_override_sections (
  id bigint generated by default as identity primary key,
  override_section_key text not null unique check (length(btrim(override_section_key)) > 0),
  override_row_id bigint not null references menu_content.menu_overrides(id) on delete cascade,
  section_id text not null check (section_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  order_index integer not null check (order_index >= 0),
  unique (override_row_id, section_id),
  unique (override_row_id, order_index)
);

create table if not exists menu_content.menu_override_groups (
  id bigint generated by default as identity primary key,
  override_group_key text not null unique check (length(btrim(override_group_key)) > 0),
  override_section_row_id bigint not null references menu_content.menu_override_sections(id) on delete cascade,
  group_id text not null check (group_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  pricing_key text null references menu_content.menu_prices(pricing_key),
  note text null,
  order_index integer not null check (order_index >= 0),
  unique (override_section_row_id, group_id),
  unique (override_section_row_id, order_index)
);

create table if not exists menu_content.menu_override_section_items (
  id bigint generated by default as identity primary key,
  override_section_item_key text not null unique check (length(btrim(override_section_item_key)) > 0),
  override_section_row_id bigint not null references menu_content.menu_override_sections(id) on delete cascade,
  item_id text not null check (item_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  available boolean null,
  pricing_key text null references menu_content.menu_prices(pricing_key),
  note text null,
  order_index integer not null check (order_index >= 0),
  unique (override_section_row_id, item_id),
  unique (override_section_row_id, order_index)
);

create table if not exists menu_content.menu_override_group_items (
  id bigint generated by default as identity primary key,
  override_group_item_key text not null unique check (length(btrim(override_group_item_key)) > 0),
  override_group_row_id bigint not null references menu_content.menu_override_groups(id) on delete cascade,
  item_id text not null check (item_id ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  available boolean null,
  pricing_key text null references menu_content.menu_prices(pricing_key),
  note text null,
  order_index integer not null check (order_index >= 0),
  unique (override_group_row_id, item_id),
  unique (override_group_row_id, order_index)
);

revoke all on all tables in schema menu_content from anon, authenticated;
revoke all on all sequences in schema menu_content from anon, authenticated;
