create table if not exists menu_content.menu_catalog_item_images (
  id bigint generated by default as identity primary key,
  catalog_item_id bigint not null references menu_content.menu_catalog_items(id) on delete cascade,
  image_path text not null check (length(btrim(image_path)) > 0),
  order_index integer not null check (order_index >= 0),
  unique (catalog_item_id, image_path),
  unique (catalog_item_id, order_index)
);

insert into menu_content.menu_catalog_item_images (
  catalog_item_id,
  image_path,
  order_index
)
select
  item.id,
  '/uploads/menu/pure-batata.webp',
  1
from menu_content.menu_catalog_items item
where item.group_id = ''
  and item.item_id = 'pure'
on conflict (catalog_item_id, image_path)
do update set order_index = excluded.order_index;
