begin;

alter table app_private.menu_publish_requests
  add column change_event_count integer not null default 0
    check (change_event_count >= 0);

create table app_private.menu_change_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  changed_by uuid null references auth.users(id) on delete set null,
  operation text not null check (
    operation ~ '^[a-z0-9_]+$'
    and length(operation) <= 80
  ),
  operation_input jsonb not null check (jsonb_typeof(operation_input) = 'object'),
  result_message text not null check (
    length(btrim(result_message)) > 0
    and length(result_message) <= 120
  ),
  menu_content_hash text null check (
    menu_content_hash is null
    or menu_content_hash ~ '^[a-f0-9]{32}$'
  ),
  publish_request_id bigint null references app_private.menu_publish_requests(id) on delete set null
);

create index menu_change_events_publish_request_idx
  on app_private.menu_change_events (publish_request_id, created_at, id);

create index menu_change_events_changed_by_idx
  on app_private.menu_change_events (changed_by, created_at desc);

create index menu_change_events_unpublished_idx
  on app_private.menu_change_events (created_at, id)
  where publish_request_id is null;

alter table app_private.menu_change_events enable row level security;

create or replace function app_private.record_menu_change_event(
  change_operation text,
  operation_input jsonb,
  result_message text
)
returns void
language plpgsql
security definer
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
declare
  current_user_id uuid := (select auth.uid());
  normalized_operation text := nullif(btrim(change_operation), '');
  normalized_message text := left(coalesce(nullif(btrim(result_message), ''), 'change_applied'), 120);
begin
  if current_user_id is null then
    return;
  end if;

  if not public.can_edit_menu_content() then
    return;
  end if;

  if normalized_operation is null
    or normalized_operation !~ '^[a-z0-9_]+$'
    or length(normalized_operation) > 80 then
    return;
  end if;

  insert into app_private.menu_change_events (
    changed_by,
    operation,
    operation_input,
    result_message,
    menu_content_hash
  )
  values (
    current_user_id,
    normalized_operation,
    coalesce(operation_input, '{}'::jsonb),
    normalized_message,
    app_private.get_menu_publication_content_hash()
  );
end;
$function$;

create or replace function public.set_profile_service_kind(profile_id text, service_kind text)
returns table(ok boolean, changed boolean, requires_redeploy boolean, operation text, message text)
language plpgsql
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
begin
  select result.ok, result.changed, result.requires_redeploy, result.operation, result.message
  into ok, changed, requires_redeploy, operation, message
  from app_private.set_profile_service_kind($1, $2) result;

  if ok and changed and requires_redeploy then
    perform app_private.record_menu_change_event(
      operation,
      jsonb_build_object(
        'profile_id', $1,
        'service_kind', $2
      ),
      message
    );
  end if;

  return next;
end;
$function$;

create or replace function public.set_daily_menu(
  regular_name text,
  regular_description text,
  vegetarian_name text,
  vegetarian_description text
)
returns table(ok boolean, changed boolean, requires_redeploy boolean, operation text, message text)
language plpgsql
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
begin
  select result.ok, result.changed, result.requires_redeploy, result.operation, result.message
  into ok, changed, requires_redeploy, operation, message
  from app_private.set_daily_menu($1, $2, $3, $4) result;

  if ok and changed and requires_redeploy then
    perform app_private.record_menu_change_event(
      operation,
      jsonb_build_object(
        'regular_name', $1,
        'regular_description', $2,
        'vegetarian_name', $3,
        'vegetarian_description', $4
      ),
      message
    );
  end if;

  return next;
end;
$function$;

create or replace function public.set_global_fixed_price(pricing_key text, amount integer)
returns table(ok boolean, changed boolean, requires_redeploy boolean, operation text, message text)
language plpgsql
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
begin
  select result.ok, result.changed, result.requires_redeploy, result.operation, result.message
  into ok, changed, requires_redeploy, operation, message
  from app_private.set_global_fixed_price($1, $2) result;

  if ok and changed and requires_redeploy then
    perform app_private.record_menu_change_event(
      operation,
      jsonb_build_object(
        'pricing_key', $1,
        'amount', $2
      ),
      message
    );
  end if;

  return next;
end;
$function$;

create or replace function public.set_global_price_variant(pricing_key text, variant_id text, amount integer)
returns table(ok boolean, changed boolean, requires_redeploy boolean, operation text, message text)
language plpgsql
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
begin
  select result.ok, result.changed, result.requires_redeploy, result.operation, result.message
  into ok, changed, requires_redeploy, operation, message
  from app_private.set_global_price_variant($1, $2, $3) result;

  if ok and changed and requires_redeploy then
    perform app_private.record_menu_change_event(
      operation,
      jsonb_build_object(
        'pricing_key', $1,
        'variant_id', $2,
        'amount', $3
      ),
      message
    );
  end if;

  return next;
end;
$function$;

create or replace function public.add_catalog_item(
  section_id text,
  item_id text,
  name text,
  description text,
  amount integer
)
returns table(ok boolean, changed boolean, requires_redeploy boolean, operation text, message text)
language plpgsql
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
declare
  target_section_id text := nullif(btrim(add_catalog_item.section_id), '');
  generated_item_id text := app_private.generate_admin_id('item');
  ignored_item_id text := nullif(btrim(add_catalog_item.item_id), '');
begin
  if ignored_item_id is not null then
    null;
  end if;

  if not public.can_edit_menu_content() then
    return query select false, false, true, 'add_catalog_item', 'permission_denied';
    return;
  end if;

  if target_section_id in ('tartas-tortillas-omelettes', 'empanadas') then
    return query select false, false, true, 'add_catalog_item', 'catalog_item_locked';
    return;
  end if;

  select result.ok, result.changed, result.requires_redeploy, result.operation, result.message
  into ok, changed, requires_redeploy, operation, message
  from app_private.add_catalog_item($1, generated_item_id, $3, $4, $5) result;

  if ok and changed and requires_redeploy then
    perform app_private.record_menu_change_event(
      operation,
      jsonb_build_object(
        'section_id', $1,
        'item_id', generated_item_id,
        'name', $3,
        'description', $4,
        'amount', $5
      ),
      message
    );
  end if;

  return next;
end;
$function$;

create or replace function public.delete_catalog_item(section_id text, item_id text)
returns table(ok boolean, changed boolean, requires_redeploy boolean, operation text, message text)
language plpgsql
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
begin
  if not public.can_edit_menu_content() then
    return query select false, false, true, 'delete_catalog_item', 'permission_denied';
    return;
  end if;

  if nullif(btrim(delete_catalog_item.section_id), '') in ('tartas-tortillas-omelettes', 'empanadas') then
    return query select false, false, true, 'delete_catalog_item', 'catalog_item_locked';
    return;
  end if;

  select result.ok, result.changed, result.requires_redeploy, result.operation, result.message
  into ok, changed, requires_redeploy, operation, message
  from app_private.delete_catalog_item($1, $2) result;

  if ok and changed and requires_redeploy then
    perform app_private.record_menu_change_event(
      operation,
      jsonb_build_object(
        'section_id', $1,
        'item_id', $2
      ),
      message
    );
  end if;

  return next;
end;
$function$;

create or replace function public.update_catalog_item(section_id text, item_id text, name text, description text)
returns table(ok boolean, changed boolean, requires_redeploy boolean, operation text, message text)
language plpgsql
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
begin
  if not public.can_edit_menu_content() then
    return query select false, false, true, 'update_catalog_item', 'permission_denied';
    return;
  end if;

  if nullif(btrim(update_catalog_item.section_id), '') in ('tartas-tortillas-omelettes', 'empanadas') then
    return query select false, false, true, 'update_catalog_item', 'catalog_item_locked';
    return;
  end if;

  select result.ok, result.changed, result.requires_redeploy, result.operation, result.message
  into ok, changed, requires_redeploy, operation, message
  from app_private.update_catalog_item($1, $2, $3, $4) result;

  if ok and changed and requires_redeploy then
    perform app_private.record_menu_change_event(
      operation,
      jsonb_build_object(
        'section_id', $1,
        'item_id', $2,
        'name', $3,
        'description', $4
      ),
      message
    );
  end if;

  return next;
end;
$function$;

create or replace function public.add_catalog_item_option(section_id text, item_id text, option_id text, name text)
returns table(ok boolean, changed boolean, requires_redeploy boolean, operation text, message text)
language plpgsql
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
declare
  generated_option_id text := app_private.generate_admin_id('option');
begin
  select result.ok, result.changed, result.requires_redeploy, result.operation, result.message
  into ok, changed, requires_redeploy, operation, message
  from app_private.add_catalog_item_option($1, $2, generated_option_id, $4) result;

  if ok and changed and requires_redeploy then
    perform app_private.record_menu_change_event(
      operation,
      jsonb_build_object(
        'section_id', $1,
        'item_id', $2,
        'option_id', generated_option_id,
        'name', $4
      ),
      message
    );
  end if;

  return next;
end;
$function$;

create or replace function public.delete_catalog_item_option(section_id text, item_id text, option_id text)
returns table(ok boolean, changed boolean, requires_redeploy boolean, operation text, message text)
language plpgsql
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
begin
  select result.ok, result.changed, result.requires_redeploy, result.operation, result.message
  into ok, changed, requires_redeploy, operation, message
  from app_private.delete_catalog_item_option($1, $2, $3) result;

  if ok and changed and requires_redeploy then
    perform app_private.record_menu_change_event(
      operation,
      jsonb_build_object(
        'section_id', $1,
        'item_id', $2,
        'option_id', $3
      ),
      message
    );
  end if;

  return next;
end;
$function$;

create or replace function public.update_catalog_item_option(section_id text, item_id text, option_id text, name text)
returns table(ok boolean, changed boolean, requires_redeploy boolean, operation text, message text)
language plpgsql
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
begin
  select result.ok, result.changed, result.requires_redeploy, result.operation, result.message
  into ok, changed, requires_redeploy, operation, message
  from app_private.update_catalog_item_option($1, $2, $3, $4) result;

  if ok and changed and requires_redeploy then
    perform app_private.record_menu_change_event(
      operation,
      jsonb_build_object(
        'section_id', $1,
        'item_id', $2,
        'option_id', $3,
        'name', $4
      ),
      message
    );
  end if;

  return next;
end;
$function$;

create or replace function public.add_grill_item(
  family_id text,
  item_id text,
  name text,
  variant_name text,
  amount integer
)
returns table(ok boolean, changed boolean, requires_redeploy boolean, operation text, message text)
language plpgsql
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
declare
  generated_item_id text := app_private.generate_admin_id('grill-item');
begin
  select result.ok, result.changed, result.requires_redeploy, result.operation, result.message
  into ok, changed, requires_redeploy, operation, message
  from app_private.add_grill_item($1, generated_item_id, $3, $4, $5) result;

  if ok and changed and requires_redeploy then
    perform app_private.record_menu_change_event(
      operation,
      jsonb_build_object(
        'family_id', $1,
        'item_id', generated_item_id,
        'name', $3,
        'variant_name', $4,
        'amount', $5
      ),
      message
    );
  end if;

  return next;
end;
$function$;

create or replace function public.delete_grill_item(item_id text)
returns table(ok boolean, changed boolean, requires_redeploy boolean, operation text, message text)
language plpgsql
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
begin
  select result.ok, result.changed, result.requires_redeploy, result.operation, result.message
  into ok, changed, requires_redeploy, operation, message
  from app_private.delete_grill_item($1) result;

  if ok and changed and requires_redeploy then
    perform app_private.record_menu_change_event(
      operation,
      jsonb_build_object('item_id', $1),
      message
    );
  end if;

  return next;
end;
$function$;

create or replace function public.update_grill_item(item_id text, name text, variant_name text)
returns table(ok boolean, changed boolean, requires_redeploy boolean, operation text, message text)
language plpgsql
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
begin
  select result.ok, result.changed, result.requires_redeploy, result.operation, result.message
  into ok, changed, requires_redeploy, operation, message
  from app_private.update_grill_item($1, $2, $3) result;

  if ok and changed and requires_redeploy then
    perform app_private.record_menu_change_event(
      operation,
      jsonb_build_object(
        'item_id', $1,
        'name', $2,
        'variant_name', $3
      ),
      message
    );
  end if;

  return next;
end;
$function$;

create or replace function public.add_grill_product(
  family_id text,
  title text,
  item_id text,
  variant_name text,
  amount integer
)
returns table(ok boolean, changed boolean, requires_redeploy boolean, operation text, message text)
language plpgsql
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
declare
  generated_family_id text := app_private.generate_admin_id('grill-product');
  generated_item_id text := app_private.generate_admin_id('grill-item');
begin
  select result.ok, result.changed, result.requires_redeploy, result.operation, result.message
  into ok, changed, requires_redeploy, operation, message
  from app_private.add_grill_product(generated_family_id, $2, generated_item_id, $4, $5) result;

  if ok and changed and requires_redeploy then
    perform app_private.record_menu_change_event(
      operation,
      jsonb_build_object(
        'family_id', generated_family_id,
        'title', $2,
        'item_id', generated_item_id,
        'variant_name', $4,
        'amount', $5
      ),
      message
    );
  end if;

  return next;
end;
$function$;

create or replace function public.delete_grill_product(family_id text)
returns table(ok boolean, changed boolean, requires_redeploy boolean, operation text, message text)
language plpgsql
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
begin
  select result.ok, result.changed, result.requires_redeploy, result.operation, result.message
  into ok, changed, requires_redeploy, operation, message
  from app_private.delete_grill_product($1) result;

  if ok and changed and requires_redeploy then
    perform app_private.record_menu_change_event(
      operation,
      jsonb_build_object('family_id', $1),
      message
    );
  end if;

  return next;
end;
$function$;

create or replace function public.update_grill_product(family_id text, title text)
returns table(ok boolean, changed boolean, requires_redeploy boolean, operation text, message text)
language plpgsql
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
begin
  select result.ok, result.changed, result.requires_redeploy, result.operation, result.message
  into ok, changed, requires_redeploy, operation, message
  from app_private.update_grill_product($1, $2) result;

  if ok and changed and requires_redeploy then
    perform app_private.record_menu_change_event(
      operation,
      jsonb_build_object(
        'family_id', $1,
        'title', $2
      ),
      message
    );
  end if;

  return next;
end;
$function$;

create or replace function public.complete_menu_publish_request(
  request_id bigint,
  publish_status text,
  publish_message text,
  vercel_status_code integer,
  vercel_job_id text
)
returns table(completed boolean, message text)
language plpgsql
security definer
set search_path to 'public', 'app_private', 'pg_temp'
as $function$
declare
  updated_count integer := 0;
  linked_change_count integer := 0;
  request_created_at timestamptz;
  normalized_status text := nullif(btrim(publish_status), '');
  normalized_message text := left(coalesce(nullif(btrim(publish_message), ''), 'publish_completed'), 120);
  normalized_vercel_job_id text := nullif(btrim(vercel_job_id), '');
begin
  if request_id is null then
    return query select false, 'request_id_required'::text;
    return;
  end if;

  if normalized_status not in ('succeeded', 'failed') then
    return query select false, 'invalid_publish_status'::text;
    return;
  end if;

  if vercel_status_code is not null and (vercel_status_code < 100 or vercel_status_code > 599) then
    return query select false, 'invalid_vercel_status_code'::text;
    return;
  end if;

  update app_private.menu_publish_requests request
  set
    status = normalized_status,
    message = normalized_message,
    vercel_status_code = complete_menu_publish_request.vercel_status_code,
    vercel_job_id = normalized_vercel_job_id,
    completed_at = now(),
    updated_at = now()
  where request.id = complete_menu_publish_request.request_id
    and request.status = 'queued'
  returning request.created_at into request_created_at;

  get diagnostics updated_count = row_count;

  if updated_count = 0 then
    return query select false, 'request_not_queued'::text;
    return;
  end if;

  if normalized_status = 'succeeded' then
    update app_private.menu_change_events event
    set publish_request_id = complete_menu_publish_request.request_id
    where event.publish_request_id is null
      and event.created_at <= request_created_at;

    get diagnostics linked_change_count = row_count;

    update app_private.menu_publish_requests request
    set
      change_event_count = linked_change_count,
      updated_at = now()
    where request.id = complete_menu_publish_request.request_id;
  end if;

  return query select true, 'publish_request_completed'::text;
end;
$function$;

revoke all on app_private.menu_change_events from public, anon, authenticated;
revoke all on sequence app_private.menu_change_events_id_seq from public, anon, authenticated;

revoke all on function app_private.record_menu_change_event(text,jsonb,text)
  from public, anon, authenticated, service_role;
grant execute on function app_private.record_menu_change_event(text,jsonb,text)
  to authenticated;

commit;
